// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import {Livro}  from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {

  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];
  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros()
      .then(livros => {
        this.livros = livros;
      })
      .catch(erro => {
        console.error("Erro ao obter livros", erro);
      });
  }

  excluir = (codigo: string): void => {
    console.log("Excluir livro com código:", codigo)
    this.servLivros.excluir(codigo)
      .then(() => {
        return this.servLivros.obterLivros();
      })
      .then(livros => {
        this.livros = livros;
      })
      .catch(erro => {
        console.error("Erro ao excluir livro", erro);
      });
  };

  obterNome = (codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}
<main class="container mt-4">
    <h1 class="mb-4 text-center text-dark">Catálogo de Livros</h1>
  
    <table class="table table-striped table-hover">
      <thead class="table-dark">
        <tr>
          <th class="col-2 text-center">Título</th>
          <th class="col-6">Resumo</th>
          <th class="col-2 text-center">Editora</th>
          <th class="col-2 text-center">Autores</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>
            <div class="d-flex flex-column align-items-center">
              <span class="fw-bold">{{ livro.titulo }}</span>
              <button 
                class="btn btn-sm btn-danger mt-2" 
                (click)="excluir(livro._id ? livro._id : '')"
              >
                Excluir
              </button>
            </div>
          </td>
          <td>{{ livro.resumo }}</td>
          <td class="text-center">{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul class="list-unstyled">
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </main>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import ControleEditora, { editoras } from './controle/ControleEditora';
import ControleLivro from './controle/ControleLivro';

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora(editoras);

const LinhaLivro = (props) => {
    const { livro, excluir } = props;

    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    return (
        <tr>
            <td>
                <div>{livro.titulo}</div>
                <button className="btn btn-danger btn-sm" onClick={() => excluir(livro._id)}>
                    Excluir
                </button>
            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>
                <ul className="list-unstyled">
                    {livro.autores.map((autor, index) => (
                        <li key={index}>{autor}</li>
                    ))}
                </ul>
            </td>
        </tr>
    );
};

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        if (!carregado) {
            controleLivro.obterLivros()
                .then((dados) => {
                    setLivros(dados);
                    setCarregado(true);
                })
                .catch((erro) => {
                    console.error("Erro ao carregar livros:", erro);
                });
        }
    }, [carregado]);

    const excluir = (id) => {
        controleLivro.excluir(id)
            .then((sucesso) => {
                if (sucesso) {
                    setLivros((livros) => livros.filter((livro) => livro._id !== id));
                }
            })
            .catch((erro) => {
                console.error("Erro ao excluir livro:", erro);
            });
    };

    return (
        <main className="container my-4">
            <h1 className="mb-4">Catálogo de Livros</h1>
            <table className="table table-striped table-bordered table-hover">
                <thead className="table-dark">
                    <tr>
                        <th className="col-2">Título</th>
                        <th className="col-6">Resumo</th>
                        <th className="col-2">Editora</th>
                        <th className="col-2">Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro) => (
                        <LinhaLivro
                            key={livro._id}
                            livro={livro}
                            excluir={excluir}
                        />
                    ))}
                </tbody>
            </table>
        </main>
    );
};

export default LivroLista;
